universe = vanilla
executable = job.sh
folder = output_training_fromEOStrees
arguments = $(Signal) $(Mass) $(Year) $(folder)
+JobFlavour = "testmatch"
output = output/classif.$(ClusterId).$(ProcId).out
error = output/classif.$(ClusterId).$(ProcId).err
log = output/classif.$(ClusterId).$(ProcId).log
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_output = True
transfer_input_files = trainMVAHHbbgg.py
queue
